name: backup-selection-role
on:
  pull_request:
    branches:
    - main
    paths:
    - backup-selection-role/**
    types:
    - closed
    - opened
    - reopened
    - synchronize
jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    concurrency: ${{ github.workflow }}
    with:
      module: backup-selection-role
    permissions:
      checks: write
      contents: read
      id-token: write
      pull-requests: write
