name: central-backup-policy
on:
  pull_request:
    branches:
    - main
    paths:
    - central-backup-policy/**
    types:
    - closed
    - opened
    - reopened
    - synchronize
jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    concurrency: ${{ github.workflow }}
    with:
      module: central-backup-policy
    permissions:
      checks: write
      contents: read
      id-token: write
      pull-requests: write
